What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences

 1. NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
 2. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
 3. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
 4. A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [3]:
import numpy as np

In [6]:
# 1-D array ==> VECTOR
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
# 2-D array ==> Metric
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 3-D array ==> Tensor
c=np.array([[[1,2],[3,4],[5,6]]])
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [14]:
# can create numpy array data type of our own
d=np.array([1,2,3],dtype=float)
d

array([1., 2., 3.])

In [15]:
# np.arange
np.arange(1,10) # range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,2) # range

array([1, 3, 5, 7, 9])

In [22]:
# reshaping the numpy array
np.arange(1,11).reshape(5,2) #(row , col)
# the product of the reshape should be equal to the no of items present in the array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
# np.ones ==> creating a list of array which contains only 1
np.ones((3,4)) #rows and col

# use_case ==> used in Deep Learning : Neural Networks

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# np.zeros ==> creating a list of array which contains only 0
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# np.random ==> generating random numbers
np.random.random((3,4))

array([[0.02882079, 0.11328461, 0.54334274, 0.04086155],
       [0.52240548, 0.56849048, 0.65423079, 0.83438643],
       [0.55111059, 0.88534539, 0.48493316, 0.63005793]])

In [27]:
# np.linspace : linearSpace ==> generates points in equal distance in given range
np.linspace(5,20,10) #(lower, higher, no of items)

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [29]:
# np.identity ==> Creating identity Metrices
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [31]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [36]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
# ndim ==> No of Dimensions
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [44]:
# shape ==> tells about how many rows and columns
a1.shape

(10,)

In [45]:
a2.shape

(3, 4)

In [47]:
a3.shape
# (2,2,2) (no.of 2D arrays, rows in each 2D array, cols in each 2D array)

(2, 2, 2)

In [48]:
# size ==> no of items
a3.size

8

In [49]:
# itemsize ==> tells the size of the memory each items contains
a1.itemsize

4

In [50]:
a3.itemsize

4

In [51]:
a2.itemsize

4

In [52]:
# dtype ==> tells the data type of the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


## Changing Datatype

In [54]:
# astype ==> can change the data type to save the memory
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

## Array Operations

In [56]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [57]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [59]:
# scalar operation ==> operating with a single number

#arithmatic
a1 * 2 # metric * scalar ==> all the iterms will multiple by two

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [60]:
a2*5

array([[ 60,  65,  70,  75],
       [ 80,  85,  90,  95],
       [100, 105, 110, 115]])

In [62]:
# relational ==> comparing with the every item
a1>6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [65]:
# vector operation ==> applying any operation on 2 arrays
a1 + a2
# shapes of the arrays should be same

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Functions

In [66]:
a1=np.random.random((3,4))
a2=np.round(a1*100)

In [67]:
a1

array([[0.29226447, 0.50222109, 0.86384237, 0.78562261],
       [0.35086758, 0.10811604, 0.14862655, 0.30602489],
       [0.69865799, 0.01918   , 0.11000182, 0.00626103]])

In [68]:
a2

array([[29., 50., 86., 79.],
       [35., 11., 15., 31.],
       [70.,  2., 11.,  1.]])

In [70]:
# max ==> maximum number
print(np.max(a1))
print(np.max(a2))

0.8638423699151758
86.0


In [73]:
print(a1.max())
print(a2.max())

0.8638423699151758
86.0


In [75]:
# min ==> Minimum number
np.min(a2)

1.0

In [76]:
# sum ==> Adding all the elements in the array
np.sum(a1)

4.191686445297472

Important : 0 --> Columns and 1 --> Rows

In [77]:
# calculating min value in each row
np.min(a1,axis=0)

array([0.29226447, 0.01918   , 0.11000182, 0.00626103])

In [78]:
np.min(a2,axis=0)

array([29.,  2., 11.,  1.])

In [79]:
a2.min(axis=0)

array([29.,  2., 11.,  1.])

In [81]:
# mean ==> average value in the array 
np.mean(a1)

0.3493072037747893

In [82]:
# median ==> mid value after sort
np.median(a2)

30.0

In [83]:
# std ==> standard deviation
np.var(a1)

0.08233778989695749

In [84]:
# trignometric functions
np.sin(a1)

array([[0.28812141, 0.48137354, 0.76034387, 0.70726547],
       [0.34371266, 0.10790553, 0.14807997, 0.30127061],
       [0.64319069, 0.01917883, 0.10978011, 0.00626099]])

In [86]:
# dot product ==> a way of combining two vectors to get a single number
a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(4,3)

print(a3)
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [87]:
# dot ==> only possible when (3,4) 4 == 4 (4,3) ==> (3,3)
np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [89]:
# log ==> calculating log of each item 
np.log(a1)

array([[-1.23009616, -0.68871484, -0.14636497, -0.24127875],
       [-1.04734639, -2.22455021, -1.90631847, -1.18408884],
       [-0.35859393, -3.95388707, -2.20725836, -5.07341039]])

In [91]:
# exponent ==> exponent value
np.exp(a1)

array([[1.33945722, 1.6523873 , 2.3722583 , 2.19377237],
       [1.42029924, 1.11417702, 1.16023962, 1.35801611],
       [2.01105205, 1.01936512, 1.1162801 , 1.00628067]])

In [94]:
# round ==> rounding of to nearest integer 
# floor ==> 6.9 --> 6
# ceil ==> 7.1 --> 8

In [95]:
np.round(a1)

array([[0., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [96]:
np.floor(a1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
np.ceil(a1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Indexing and Slicing

In [99]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [100]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


Indexing

In [102]:
# findng the last element
a1[-1]

9

In [104]:
a2[1][2]

6

In [106]:
# another method
a2[2,3] # [row,col]

11

In [107]:
a3[1][0][1]

5

In [109]:
# another
a3[1,0,1] #[which 2D array,row,col]

5

In [112]:
a3[0,0,0]

0

In [113]:
a3[1,1,0]

6

Slicing

In [115]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
# fecth [2,3,4]
a1[2:5] #range

array([2, 3, 4])

In [117]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
# find the 1st row
a2[0,:]

array([0, 1, 2, 3])

In [125]:
# find the third col.
a2[:,2] #: --> leads to the row for the range

array([ 2,  6, 10])

In [127]:
# calculate
# [
#    [5,6]
#    [9,10]
# ]

a2[1:,1:3] #[rows,columns]

array([[ 5,  6],
       [ 9, 10]])

In [129]:
# calculate
# [
#    [0,3]
#    [8,11]
# ]
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [141]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
# calculate
# [
#    [1,3]
#    [9,11]
# ]
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [143]:
#calculate [4,7]
a2[1,0::3]

array([4, 7])

In [145]:
# calculate
# [
#    [1,2,3]
#    [5,6,7]
# ]
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [147]:
a3=np.arange(27).reshape(3,3,3)

In [148]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [149]:
# calculate
# [[ 9, 10, 11],
# [12, 13, 14],
# [15, 16, 17]],
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [150]:
# calculate first and last 2-D array
a3[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [153]:
# calculate
# [3,4,5]
a3[0,1]

array([3, 4, 5])

In [154]:
# claculate 2nd numpr-array mid col.
# [[10],[13],[16]]
a3[1,:,1:2]

array([[10],
       [13],
       [16]])

In [156]:
# calculate 
# [[22,23],[25,26]]
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [157]:
# calculate 
# [[0,2],[18,20]]
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [158]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [160]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [161]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [162]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [163]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [165]:
# printing all the items
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [166]:
# reshape

In [167]:
# transpose ==> (3,4) --> (4,3)
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [168]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [169]:
# ravel ==> converting any Dimension of array into 1-D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking

Shape should be same while Stacking

In [178]:
# horizontal stack ==> joining of two array like (2,2) hstack (2,2) --> (2,4) 

In [179]:
a5=np.arange(12).reshape(3,4)
a6=np.arange(12,24).reshape(3,4)

In [180]:
np.hstack((a5,a6))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [181]:
# vertical stack ==> joining of two array like (2,2) hstack (2,2) --> (4,2) 

In [182]:
np.vstack((a5,a6))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [184]:
# horizontal split
np.hsplit(a5,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [186]:
# vertical split
np.vsplit(a5,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]