In [1]:
import numpy as np

np.sort : for sorting the array

In [2]:
a=np.random.randint(10,100,20)
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [3]:
np.sort(a)

array([19, 20, 24, 28, 29, 29, 34, 46, 53, 56, 57, 60, 64, 71, 72, 74, 80,
       80, 83, 94])

In [4]:
# decending order
np.sort(a)[::-1]

array([94, 83, 80, 80, 74, 72, 71, 64, 60, 57, 56, 53, 46, 34, 29, 29, 28,
       24, 20, 19])

In [5]:
b=np.random.randint(10,100,20).reshape(5,4)
b

array([[38, 32, 21, 67],
       [21, 95, 81, 45],
       [46, 35, 42, 58],
       [61, 32, 97, 68],
       [31, 27, 76, 68]])

In [6]:
# row-wise
np.sort(b)

array([[21, 32, 38, 67],
       [21, 45, 81, 95],
       [35, 42, 46, 58],
       [32, 61, 68, 97],
       [27, 31, 68, 76]])

In [7]:
# column-wise
np.sort(b,axis=0)

array([[21, 27, 21, 45],
       [31, 32, 42, 58],
       [38, 32, 76, 67],
       [46, 35, 81, 68],
       [61, 95, 97, 68]])

np.append : The numpy.append() appends values along the mentioned axis at the end of the array

In [8]:
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [9]:
np.append(a,200)

array([ 71,  60,  24,  53,  94,  56,  80,  46,  20,  28,  80,  83,  29,
        64,  72,  19,  34,  74,  57,  29, 200])

In [10]:
# 2-D array
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[38., 32., 21., 67.,  1.],
       [21., 95., 81., 45.,  1.],
       [46., 35., 42., 58.,  1.],
       [61., 32., 97., 68.,  1.],
       [31., 27., 76., 68.,  1.]])

np.concatenate : numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [11]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
# columns
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique : With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [14]:
e=np.array([1,1,1,2,2,2,3,3,4,4,5,5,5,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims : With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [15]:
a # 1-D array

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [16]:
np.expand_dims(a,axis=0) # 2-D array 

array([[71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19,
        34, 74, 57, 29]])

np.where : The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [17]:
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [18]:
# give the indexes of those value which are greater than 50
np.where(a>50)

(array([ 0,  1,  3,  4,  5,  6, 10, 11, 13, 14, 17, 18], dtype=int64),)

In [19]:
# replacing the numbers with 0 which are greater than 50
# np.where(condition,True,False)
np.where(a>50,0,a)

array([ 0,  0, 24,  0,  0,  0,  0, 46, 20, 28,  0,  0, 29,  0,  0, 19, 34,
        0,  0, 29])

In [20]:
# replacing even numbers with 0
np.where(a%2==0,0,a)

array([71,  0,  0, 53,  0,  0,  0,  0,  0,  0,  0, 83, 29,  0,  0, 19,  0,
        0, 57, 29])

np.argmax : The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [21]:
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [22]:
# calculating the index of max element
np.argmax(a)

4

In [23]:
b

array([[38, 32, 21, 67],
       [21, 95, 81, 45],
       [46, 35, 42, 58],
       [61, 32, 97, 68],
       [31, 27, 76, 68]])

In [24]:
np.argmax(b,axis=1)

array([3, 1, 3, 2, 2], dtype=int64)

In [25]:
# argmin
np.argmin(a)

15

np.cumsum : numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [26]:
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [27]:
np.cumsum(a)

array([  71,  131,  155,  208,  302,  358,  438,  484,  504,  532,  612,
        695,  724,  788,  860,  879,  913,  987, 1044, 1073], dtype=int32)

In [28]:
np.cumsum(b,axis=0)

array([[ 38,  32,  21,  67],
       [ 59, 127, 102, 112],
       [105, 162, 144, 170],
       [166, 194, 241, 238],
       [197, 221, 317, 306]], dtype=int32)

In [29]:
# cumprod : for multiplication
np.cumprod(a)

array([         71,        4260,      102240,     5418720,   509359680,
       -1540628992,  1303732224,  -157859840,  1137770496,  1792802816,
        1690304512, -1438646272,  1228931072,  1342177280, -2147483648,
       -2147483648,           0,           0,           0,           0],
      dtype=int32)

np.percentile : numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [30]:
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [31]:
np.percentile(a,100) #(arrays, percintile rank)

94.0

In [32]:
np.percentile(a,50)

56.5

np.histogram : Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [33]:
# tells a frequency count
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 5, 1, 1, 3, 2, 3, 3, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef(Correlation Coefficient) : Return Pearson product-moment correlation coefficients.

In [36]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience) #salary --> salary and expericence   experience --> salary and experience

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin : With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [37]:
# for searching multiple items
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [38]:
np.isin(a,[60,24])

array([False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [39]:
a[np.isin(a,[60,24])]

array([60, 24])

np.flip : The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [40]:
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [41]:
np.flip(a)

array([29, 57, 74, 34, 19, 72, 64, 29, 83, 80, 28, 20, 46, 80, 56, 94, 53,
       24, 60, 71])

In [42]:
b

array([[38, 32, 21, 67],
       [21, 95, 81, 45],
       [46, 35, 42, 58],
       [61, 32, 97, 68],
       [31, 27, 76, 68]])

In [44]:
np.flip(b) # rows amd columns both will be flipped

array([[68, 76, 27, 31],
       [68, 97, 32, 61],
       [58, 42, 35, 46],
       [45, 81, 95, 21],
       [67, 21, 32, 38]])

np.put : The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [45]:
a

array([71, 60, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [49]:
# 71 --> 1 and 60 --> 2
np.put(a,[0,1],[1,2]) # (array,list of indexes,number you want)

# this function performs permanent changes

In [50]:
a

array([ 1,  2, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

np.delete : The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [51]:
np.delete(a,[0])

array([ 2, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34, 74,
       57, 29])

## Set Functions

1. np.union1d
2. np.intersect1d
3. np.setdiff1d
4. np.setxor1d
5. np.in1d

In [52]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n) # all unique elements

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
np.intersect1d(m,n) # same elements

array([3, 4, 5])

In [55]:
np.setdiff1d(m,n) # all items which are present in m and not in n

array([1, 2])

In [57]:
np.setxor1d(m,n) # remove common elements in both

array([1, 2, 6, 7])

In [59]:
np.in1d(m,n) # comparing m from n

array([False, False,  True,  True,  True])

np.clip : numpy.clip() function is used to Clip (limit) the values in an array.

In [60]:
a

array([ 1,  2, 24, 53, 94, 56, 80, 46, 20, 28, 80, 83, 29, 64, 72, 19, 34,
       74, 57, 29])

In [63]:
np.clip(a,a_min=53,a_max=80) 

# all values which are less than 53 will clipped to 53 and greater than 80 will clipped to 80

array([53, 53, 53, 53, 80, 56, 80, 53, 53, 53, 80, 80, 53, 64, 72, 53, 53,
       74, 57, 53])