In [2]:
import numpy as np

### `Q-1:` Create a null vector of size 10 but the fifth value which is 1.

In [3]:
a=np.nan*np.arange(10)

In [4]:
a

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [5]:
a[4]=1

In [6]:
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2:` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [8]:
(a,b)=map(int,input("Enter the 2 numbers: ").split())

a1=np.random.random((a,b))
print(a1)
print(np.mean(a1))

Enter the 2 numbers:  4 3
[[0.50635756 0.22860832 0.01733715]
 [0.54228133 0.83387712 0.71696291]
 [0.57491928 0.32508423 0.27115315]
 [0.02687666 0.26398324 0.78585067]]
0.42444096871326714


### `Q-3:` Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [9]:
# Example :
# [[1,1,1,1],
# [1,0,0,1],
# [1,0,0,1],
# [1,1,1,1]]

In [10]:
def array(a,b):
    x=np.ones((a,b))
    x[1:3,1:3]=0
    
    return x
array(4,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

### `Q-4:` Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [11]:
np.linspace(0,1,10)[1:-1]

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

### `Q-5:` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [12]:
#Code here
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

#Identy matrix of size 3-- 3X3
np.eye(3)

#Identy matrix of size 4-- 4X4
np.identity(4)

# eye and identity are same.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [13]:
z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [14]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### `Q-8:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [32]:
a=list(map(int,input("Enter an array: ").split()))
np.flip(a).astype(float)

Enter an array: 1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-9:` Elements count

Count the number of elements of a numpy array.

**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [35]:
a = np.array([])
a = np.array([1, 2])
a = np.zeros((2,3))
a.size

6

### `Q-10:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function

In [38]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s
softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-11:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [40]:
def vertical_stack(*args):
    for i in args:
        if type(i)!=np.ndarray:
            raise TypeError ("Requires Numpy Array")
    return np.vstack(args)

In [44]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

print(vertical_stack(a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [45]:
c=np.random.random((2,5))
print(vertical_stack(a,b,c))

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.24407454 0.74918179 0.32210803 0.85349774 0.96707219]
 [0.73515723 0.73942895 0.8973201  0.13303242 0.57520822]]


### `Q-12:` Subtract the mean of each row from a matrix.

In [48]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a-np.mean(a,keepdims=True)

array([[-5.5, -4.5, -3.5, -2.5],
       [-1.5, -0.5,  0.5,  1.5],
       [ 2.5,  3.5,  4.5,  5.5]])

### `Q-13:` Swap column-1 of array with column-2 in the array.

In [51]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
x[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-14:` Replace odd elements in arrays with -1.

In [53]:
a=np.random.randint(1,100,20)
a

array([37, 83, 70, 34, 59,  7, 78, 10, 10, 72, 25, 81, 97, 69, 10, 35, 63,
       50, 40, 92])

In [55]:
a[a%2!=0]=-1

In [56]:
a

array([-1, -1, 70, 34, -1, -1, 78, 10, 10, 72, -1, -1, -1, -1, 10, -1, -1,
       50, 40, 92])

### `Q-15:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [70]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a]=b[a<b]

In [71]:
a

array([6, 3, 1, 7, 8])

### `Q-16` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```

In [73]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)

In [74]:
arr1

array([[3416, 3228, 7495, 7877, 7078],
       [2757, 8139, 7469, 7122, 7935],
       [4315, 4451, 8771, 4230, 2228],
       [7741, 6110, 1213, 3752, 5793],
       [8724, 8733, 7195, 2267, 8199],
       [ 934, 6532, 5181, 2062,  183],
       [1132, 3661, 6127, 7541,  988],
       [4712, 4554, 6107, 9805, 4457]])

In [75]:
# Fetch Every alternate column of the array
arr1[:,::2]

array([[3416, 7495, 7078],
       [2757, 7469, 7935],
       [4315, 8771, 2228],
       [7741, 1213, 5793],
       [8724, 7195, 8199],
       [ 934, 5181,  183],
       [1132, 6127,  988],
       [4712, 6107, 4457]])

In [84]:
# Normalise the given array
x=(arr1-np.min(arr1))/(np.max(arr1)-np.min(arr1))

In [85]:
x

array([[0.33600083, 0.31646227, 0.75992517, 0.79962586, 0.71658699],
       [0.26751195, 0.82685512, 0.75722303, 0.72115984, 0.80565371],
       [0.42943255, 0.44356683, 0.89253793, 0.42059863, 0.21253378],
       [0.78549158, 0.6159842 , 0.10704635, 0.37092081, 0.58303887],
       [0.88765329, 0.88858865, 0.72874662, 0.21658699, 0.83309083],
       [0.0780503 , 0.65984203, 0.51943463, 0.19528165, 0.        ],
       [0.09862814, 0.36146331, 0.61775099, 0.76470588, 0.08366244],
       [0.47069216, 0.45427146, 0.61567242, 1.        , 0.4441904 ]])

### `Q-17:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [86]:
def func(arr,n):
    arr.sort()
    if n<=len(arr):
        return arr[-n]

In [87]:
func([12,34,40,7,1,0],3)

12

In [88]:
func([12,34,40,7,1,0],1)

40